[pytest]
minversion = 7.0
addopts = -ra -q --strict-markers
testpaths = tests
python_files = test_*.py
pythonpath =
    ../ha-custom
    ..
asyncio_mode = auto
markers =
    asyncio: mark tests as asyncio tests