#!/bin/bash


set -e

WS="/workspaces"
CORE_DIR="$WS/ha-core"
CUSTOM_DIR="$WS/nsw_tas_fuel_station/custom_components/nsw_fuel_station"
CUSTOM_TEST_DIR="$WS/nsw_tas_fuel_station/tests"

CORE_COMONENT_DIR="$CORE_DIR/homeassistant/components/nsw_fuel_station"
CORE_TEST_DIR="$CORE_DIR/tests/components/nsw_fuel_station"

cd $CORE_COMONENT_DIR
rm -rf *.py manifest.json strings.json
cp $CUSTOM_DIR/*.py .
cp $CUSTOM_DIR/translations/en.json strings.json
grep -v "version" $CUSTOM_DIR/manifest.json > manifest.json
sed -i 's|"domain":.*|"domain": "nsw_fuel_station",|' manifest.json
sed -i 's|"documentation": *"[^"]*"|"documentation": "https://www.home-assistant.io/integrations/nsw_fuel_station"|' manifest.json
sed -i 's|"requirements":[[:space:]]*\[[^]]*\]|"requirements": ["nsw-tas-fuel-api-client==0.0.1"]|' manifest.json

sed -i 's|DOMAIN.*|DOMAIN = "nsw_fuel_station"|' const.py

cd $CORE_TEST_DIR
rm -f *.py
cp $CUSTOM_TEST_DIR/*.py .

sed \
  's/custom_components\.nsw_fuel_station/homeassistant.components.nsw_fuel_station/g' \
  conftest.py test_config_flow.py test_coordinator.py test_sensor.py