#!/bin/bash


set -e

WS="/workspaces"
CORE_DIR="$WS/ha-core"
CUSTOM_DIR="$WS/nsw_tas_fuel_station/custom_components/nsw_tas_fuel_station"
CUSTOM_TEST_DIR="$WS/nsw_tas_fuel_station/tests"

CORE_COMONENT_DIR="$CORE_DIR/homeassistant/components/nsw_fuel_station"
CORE_TEST_DIR="$CORE_DIR/tests/components/nsw_fuel_station"

cd $CORE_COMONENT_DIR
rm -rf *.py manifest.json translations
cp $CUSTOM_DIR/*.py .
grep -v "version" manifest.json > manifest.json
sed -i 's|"documentation": *"[^"]*"|"documentation": "https://www.home-assistant.io/integrations/nsw_fuel_station"|' manifest.json



cd $CORE_TEST_DIR
rm -f *.py
cp $CUSTOM_TEST_DIR/*.py .

sed -i.bak \
  's/custom_components\.nsw_fuel_station/homeassistant.components.nsw_fuel_station/g' \
  conftest.py test_config_flow.py test_coordinator.py test_sensor.py

for file in *.py; do
  diff "$file" "$file.bak"
done